# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nxv5DybMhT9wfuduH7EIkogUieI9rHg3
"""

#To read the csv file
import pandas as pd

df = pd.read_csv("/content/Zomato-data-.csv")

#To know no.of entries
df.info()

#Displays the first ffive rows
df.head()

#To know the null values
df.describe()

#To know the columns and rows,column names
print(df.shape)
df.columns

#To check the missing values
df.isnull().sum()

#To check the dulicate values
df.duplicated().sum()

#To check unique values
df.nunique()

#To know the data type
df.dtypes

#To remove dulicates
df.drop_duplicates(inplace=True)

#To fix the data type
df['votes'] = df['votes'].astype(int)

#Data transformation
df['rate'] = df['rate'].astype(str).str.replace('/5','').astype(float)

df['approx_cost(for two people)'] = df['approx_cost(for two people)'].astype(str).str.replace(',', '').astype(int)

#Outliers detection
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(df['approx_cost(for two people)'])
plt.show()
df = df[df['approx_cost(for two people)'] < 5000]

#Feature engineering
def cost_category(x):
    if x < 500:
        return "Low"
    elif x < 2000:
        return "Medium"
    else:
        return "High"

df['cost_category'] = df['approx_cost(for two people)'].apply(cost_category)

def rating_label(x):
    if x >= 4:
        return "Excellent"
    elif x >= 3:
        return "Good"
    else:
        return "Average"

df['rating_category'] = df['rate'].apply(rating_label)

#Cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)