# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KeoSxtE_Niw4IhlXbrbLS-0zBJXNa1-r

# Exploratory Data Analysis on ZOMATO Dataset
"""

#Read the csv
import pandas as pd
df = pd.read_csv("/content/cleaned_dataset.csv")
df.head()

#understand the dataset
df.info()
df.describe()

"""# Univariative Analysis

"""

#Histogram
df['rate'].hist()

"""**Insight**:
**“Most restaurants have ratings between 3.5–4.5”**
"""

df['approx_cost(for two people)'].hist()

"""**Insight:**
**“Most restaurants are affordable”**
"""

df['votes'].hist()

"""**Insight: "Most Restaurents have max votes"**

"""

df['listed_in(type)'].value_counts()

df['listed_in(type)'].value_counts().plot(kind='bar')

"""**Insights: "Most prefered type"**"""

df['online_order'].value_counts().plot(kind='bar')

"""**Insights:"Most ordered type"**

# Multivariative Analysis
"""

import seaborn as sns
sns.scatterplot(x='votes', y='rate', data=df)

"""**Insights:"Votes vs Rates relation"**"""

sns.heatmap(df.corr(numeric_only=True), annot=True)

"""**Insights:"Related Variables"**"""